language: minimal

git:
  depth: false

os: linux
dist: jammy

cache:
  directories:
    - $HOME/.m2

services:
  - docker

script:
  - chmod 777 deploy-maven-central.sh
  - travis_retry docker run -v $PWD:/src -v $HOME/.m2:/root/.m2 -e VAULT_TOKEN=$VAULT_TOKEN moussavdb/build-java-native ./deploy-maven-central.sh
